#!/usr/bin/evn perl
@names = qw! Don Makayla Angelo Roland Corey Austin Bailey Ryan Jeremy !;
print "Enter numbers then press Control-D: \n";
chomp(@numbers = <STDIN>);
foreach (@numbers) {
	print "@names[ $_ -1 ] \n";
} 
