#!/usr/bin/env perl
@ARGV = '/home/ec2-user/perl5/perlbrew/perls/perl-5.16.3/lib/5.16.3/pod/perlfunc.pod';
%seen;
while (<>) {
	if (/(^(=item)\s+[a-zA-z_]\w*)/) {
		$seen{$1} +=1;
		if ($seen{$1} >= 3) {
			print "Match Found, Appeared $seen{$1} times: $_\n";
		}
	} else {
	#	print "No Matches.\n";
	}
}
